---
- name: Install nginx
  hosts: all
  become: true
  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present
  - name: Install nginx
    yum:
      name: nginx
      state: present
  - name: Insert Index Page
    template:
      src: "{{INDEX}}"
      dest: /usr/share/nginx/html/index.html
  - name: Start NGINX
    service:
      name: nginx
      state: started
      enabled: true
  - name: copy the nginx config file and restart nginx
    copy:
      src: update_port.cfg
      dest: /etc/nginx/nginx.conf
    become: yes
  - name: restart nginx
    service:
      name: nginx
      state: restarted
      enabled: true
    become: yes
